parameters:

services:
    site_twig_extension:
        class: AppBundle\Twig\Extension\SiteExtension
        public: false
        tags:
            - { name: twig.extension }
        calls:
            - [setRequest, ["@?request="]]
    frontpage.repository:
        class: AppBundle\EzRepository\Frontpage
        arguments: ['@ezpublish.api.repository', '@ezpublish_legacy.config.resolver']